//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Hello.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TestHello")
#ifdef RESTRICT_TestHello
#define INCLUDE_ALL_TestHello 0
#else
#define INCLUDE_ALL_TestHello 1
#endif
#undef RESTRICT_TestHello

#if !defined (TestHello_) && (INCLUDE_ALL_TestHello || defined(INCLUDE_TestHello))
#define TestHello_

@interface TestHello : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)mark;

@end

J2OBJC_EMPTY_STATIC_INIT(TestHello)

FOUNDATION_EXPORT void TestHello_init(TestHello *self);

FOUNDATION_EXPORT TestHello *new_TestHello_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT TestHello *create_TestHello_init();

FOUNDATION_EXPORT void TestHello_mark();

J2OBJC_TYPE_LITERAL_HEADER(TestHello)

#endif

#pragma pop_macro("INCLUDE_ALL_TestHello")
